name: ✨ 功能请求
description: 建议新功能或改进
title: "[功能请求] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的建议！请填写以下信息帮助我们理解您的需求。

  - type: dropdown
    id: feature_type
    attributes:
      label: 功能类型
      description: 这个功能属于哪个类别
      options:
        - 新模型支持
        - 新功能开发
        - 性能优化
        - 文档改进
        - 工具增强
        - 其他
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: 问题或需求
      description: 描述您想要解决的问题或满足的需求
      placeholder: |
        当前在使用时遇到什么困难或限制？
        期望实现什么样的功能？
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 建议的解决方案
      description: 您希望如何实现这个功能
      placeholder: |
        详细描述您的想法或建议
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: 替代方案
      description: 是否考虑过其他解决方法
      placeholder: |
        列出您考虑过的其他方案
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 优先级（您的看法）
      description: 这个功能对您有多重要
      options:
        - 高 - 非常需要
        - 中 - 希望有
        - 低 - 可以等待
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: 使用场景
      description: 描述这个功能的具体使用场景
      placeholder: |
        您会在什么情况下使用这个功能？
        它会如何改善您的工作流程？
    validations:
      required: true

  - type: textarea
    id: examples
    attributes:
      label: 示例或参考
      description: 提供相关的示例、链接或参考
      placeholder: |
        - 类似项目的实现
        - 相关文档或论文
        - 代码示例
    validations:
      required: false

  - type: checkboxes
    id: contribute
    attributes:
      label: 贡献意愿
      description: 是否愿意为这个功能做贡献
      options:
        - label: 我愿意协助实现这个功能
        - label: 我可以提供测试和反馈
        - label: 我可以协助编写文档
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 其他可能有帮助的信息
    validations:
      required: false

