name: ❓ 问题咨询
description: 询问使用问题或寻求帮助
title: "[问题] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        感谢您的提问！请填写以下信息以便更好地帮助您。

  - type: dropdown
    id: category
    attributes:
      label: 问题分类
      description: 问题属于哪个类别
      options:
        - 环境安装
        - 模型使用
        - 代码运行
        - 部署相关
        - 文档理解
        - 其他
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: 问题描述
      description: 详细描述您的问题
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: 已尝试的方法
      description: 您已经尝试过哪些解决方法
      placeholder: |
        - 尝试1: ...
        - 尝试2: ...
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: 相关上下文
      description: 提供相关的代码、配置或截图
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 附加信息
      description: 其他可能有帮助的信息
    validations:
      required: false

